services:
  db:
    image: mysql:8.0
    container_name: saip_db_container
    restart: always
    environment:
      MYSQL_DATABASE: db_saip_proyect
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app

  backend:
    build: ./B
    container_name: saip_backend
    ports:
      - "8000:8000"
    volumes:
      - ./B:/app:Z
    environment:
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_HOST=db
      - DB_NAME=db_saip_proyect
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - app

  frontend:
    build: ./F
    container_name: saip_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./F:/src:Z
      - /src/node_modules
    depends_on:
      - backend
    networks:
      - app

volumes:
  mysql_data:

networks:
  app: