services:
  db:
    image: mysql:8.0
    container_name: saip_db_container
    restart: always
    environment:
      MYSQL_DATABASE: db_saip_proyect
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build: ./backend
    container_name: saip_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:Z
      - /app/.venv
    env_file:
      - .env
    environment:
      - UV_LINK_MODE=copy
    depends_on:
      - db
    networks:
      - app

  frontend:
    build: ./frontend
    container_name: saip_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/src:Z
      - /src/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - app

volumes:
  mysql_data:

networks:
  app: