"""rename update_at to updated_at in roles

Revision ID: 01f782c6156b
Revises: d7c5a0f5c3e5
Create Date: 2026-03-11 00:00:58.550946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '01f782c6156b'
down_revision: Union[str, Sequence[str], None] = 'd7c5a0f5c3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('roles_ibfk_1'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'users', ['updated_by'], ['id'])
    op.drop_column('roles', 'update_at')
    op.drop_column('roles', 'update_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('update_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('update_at', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('roles_ibfk_1'), 'roles', 'users', ['update_by'], ['id'])
    op.drop_column('roles', 'updated_by')
    op.drop_column('roles', 'updated_at')
    # ### end Alembic commands ###
