"""rename create_date to created_at in roles

Revision ID: 0293e096605f
Revises: 01f782c6156b
Create Date: 2026-03-11 00:15:05.947699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0293e096605f'
down_revision: Union[str, Sequence[str], None] = '01f782c6156b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "roles",          
        "create_date",     
        new_column_name="created_at",
        existing_type=sa.DateTime() 
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
