"""create table sesessions

Revision ID: 05abcdbf6e10
Revises: 8590367a8bb5
Create Date: 2026-03-07 23:45:10.153730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05abcdbf6e10'
down_revision: Union[str, Sequence[str], None] = '8590367a8bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE'),
               type_=sa.Enum('ACTIVE', 'INACTIVE', name='userstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', name='userstatus'),
               type_=mysql.ENUM('ACTIVE', 'INACTIVE'),
               existing_nullable=False)
    op.drop_table('sessions')
    # ### end Alembic commands ###
