"""delete

Revision ID: 2bd716eed439
Revises: 8590367a8bb5
Create Date: 2026-03-09 04:37:56.414653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd716eed439'
down_revision: Union[str, Sequence[str], None] = '8590367a8bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_roles_is_active'), 'roles', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_is_active'), table_name='roles')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('roles', 'is_active')
    # ### end Alembic commands ###
