"""add soft delete fields to users

Revision ID: 94dbe7b35f5d
Revises: 4b696d4e984d
Create Date: 2026-03-10 22:53:04.183743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '94dbe7b35f5d'
down_revision: Union[str, Sequence[str], None] = '4b696d4e984d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('update_by', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='rolestatus'), nullable=False))
    op.add_column('roles', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_roles_is_active'), table_name='roles')
    op.create_index(op.f('ix_roles_status'), 'roles', ['status'], unique=False)
    op.create_foreign_key(None, 'roles', 'users', ['update_by'], ['id'])
    op.create_foreign_key(None, 'roles', 'users', ['deleted_by'], ['id'])
    op.drop_column('roles', 'is_active')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['deleted_by'], ['id'])
    op.drop_column('users', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'deleted_at')
    op.add_column('roles', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_index(op.f('ix_roles_status'), table_name='roles')
    op.create_index(op.f('ix_roles_is_active'), 'roles', ['is_active'], unique=False)
    op.drop_column('roles', 'deleted_by')
    op.drop_column('roles', 'status')
    op.drop_column('roles', 'update_by')
    op.drop_column('roles', 'update_at')
    # ### end Alembic commands ###
