"""sessions add session_id and token

Revision ID: c1c21037a648
Revises: 3d4131aa3b0c
Create Date: 2026-03-15 23:30:22.722084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c1c21037a648'
down_revision: Union[str, Sequence[str], None] = '3d4131aa3b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'token',
               existing_type=mysql.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###

    # Reordenar columnas
    op.execute("ALTER TABLE sessions MODIFY COLUMN token VARCHAR(36) NOT NULL AFTER id")
    op.execute("ALTER TABLE sessions MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT FIRST")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'token',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###

    # Revertir orden
    op.execute("ALTER TABLE sessions MODIFY COLUMN token VARCHAR(36) NOT NULL AFTER is_active")
    op.execute("ALTER TABLE sessions MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT AFTER token")