"""add product_categories and commercial_products

Revision ID: 62d1217ec939
Revises: 9454cc7dacee
Create Date: 2026-06-09 04:50:02.555053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '62d1217ec939'
down_revision: Union[str, Sequence[str], None] = '9454cc7dacee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_product_category_deleted_by', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_product_category_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_product_categories_token'), 'product_categories', ['token'], unique=True)
    op.create_table('commercial_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('available_quantity', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=False),
    sa.Column('max_stock', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_commercial_product_deleted_by', use_alter=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_commercial_product_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_products_token'), 'commercial_products', ['token'], unique=True)
    op.create_foreign_key('fk_provider_contact_deleted_by', 'provider_contacts', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_provider_contact_updated_by', 'provider_contacts', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_provider_deleted_by', 'providers', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_provider_updated_by', 'providers', 'users', ['updated_by'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_provider_updated_by', 'providers', type_='foreignkey')
    op.drop_constraint('fk_provider_deleted_by', 'providers', type_='foreignkey')
    op.drop_constraint('fk_provider_contact_updated_by', 'provider_contacts', type_='foreignkey')
    op.drop_constraint('fk_provider_contact_deleted_by', 'provider_contacts', type_='foreignkey')
    op.drop_index(op.f('ix_commercial_products_token'), table_name='commercial_products')
    op.drop_table('commercial_products')
    op.drop_index(op.f('ix_product_categories_token'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
