"""add modules and role_modules tables

Revision ID: 9454cc7dacee
Revises: 765979b99700
Create Date: 2026-04-06 23:52:13.343357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9454cc7dacee'
down_revision: Union[str, Sequence[str], None] = '765979b99700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('nit', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='providerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_provider_deleted_by', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_provider_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_email'), 'providers', ['email'], unique=True)
    op.create_index(op.f('ix_providers_nit'), 'providers', ['nit'], unique=True)
    op.create_index(op.f('ix_providers_token'), 'providers', ['token'], unique=True)
    op.create_table('provider_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_provider_contact_deleted_by', use_alter=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_provider_contact_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_contacts_token'), 'provider_contacts', ['token'], unique=True)
    op.create_foreign_key('fk_production_order_deleted_by', 'production_orders', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_production_order_updated_by', 'production_orders', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_recipe_updated_by', 'recipes', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_recipe_deleted_by', 'recipes', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_unique_constraint(None, 'supplies', ['name'])
    op.create_foreign_key('fk_supply_deleted_by', 'supplies', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_supply_updated_by', 'supplies', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_supply_category_updated_by', 'supply_categories', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_supply_category_deleted_by', 'supply_categories', 'users', ['deleted_by'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_supply_category_deleted_by', 'supply_categories', type_='foreignkey')
    op.drop_constraint('fk_supply_category_updated_by', 'supply_categories', type_='foreignkey')
    op.drop_constraint('fk_supply_updated_by', 'supplies', type_='foreignkey')
    op.drop_constraint('fk_supply_deleted_by', 'supplies', type_='foreignkey')
    op.drop_constraint(None, 'supplies', type_='unique')
    op.drop_constraint('fk_recipe_deleted_by', 'recipes', type_='foreignkey')
    op.drop_constraint('fk_recipe_updated_by', 'recipes', type_='foreignkey')
    op.drop_constraint('fk_production_order_updated_by', 'production_orders', type_='foreignkey')
    op.drop_constraint('fk_production_order_deleted_by', 'production_orders', type_='foreignkey')
    op.drop_index(op.f('ix_provider_contacts_token'), table_name='provider_contacts')
    op.drop_table('provider_contacts')
    op.drop_index(op.f('ix_providers_token'), table_name='providers')
    op.drop_index(op.f('ix_providers_nit'), table_name='providers')
    op.drop_index(op.f('ix_providers_email'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
